name: ${ENV:-dev}
services:
  coffee:
    build: 
      tags:
      - lunch
      - lunch:dev
    env_file: .env.${ENV:-dev}
    environment:
    - VIRTUAL_HOST=coffee.${ENV:-dev}.lvh.me
    ports:
    - 80

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - vip:/var/lib/postgresql
    - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    environment:
    - VIRTUAL_HOST=adminer.${ENV:-dev}.lvh.me
    ports:
    - 8080

volumes:
  vip: 

networks:
  default:
    external: true
    name: infra